-- MySQL Script generated by MySQL Workbench
-- 09/07/16 11:16:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_calendar` (
  `cal_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cal_event_title` TEXT NOT NULL COMMENT '',
  `cal_date_start` DATE NOT NULL COMMENT '',
  `cal_date_end` DATE NOT NULL COMMENT '',
  `cal_created_by` INT NULL COMMENT '',
  `cal_last_update_by` INT NULL COMMENT '',
  `cal_date_last_update` DATETIME NULL COMMENT '',
  `cal_date_added` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`cal_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
