<?php

	$id = '';
	if (!empty($this->zoneconfig['conf']['id']) && !$this->prefixId)
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	else
		$id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
	
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a">
	<div class="me-heading bg-white border-bottom" id="id_meliscore_tool_user_header" data-meliskey="meliscore_tool_user_header">
    	<div class="row">
    		<div class="me-hl col-xs-12 col-sm-8 col-md-9">
    			<h1 class="content-heading"><?php echo $this->translate('tr_melistoolcalendar_tool_calendar')?></h1>
    			<p><?= $this->translate('tr_melistoolcalendar_tool_calendar_description'); ?></p>
    		</div>
      		<div class="me-hr col-xs-12 col-sm-4 col-md-3"></div>	
    	</div>
    </div>
    
	<div class="innerAll spacing-x2">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12 col-md-4 no-gutters">
					<!-- d-none d-md-block -->
					<div class="create-new-event">
						<?php echo $this->melistoolcalendar_tool_create_form; ?>
					</div>
					<div class="recently-added d-none d-md-block">
						<?php echo $this->melistoolcalendar_tool_recent_added; ?>
					</div>
                </div>   
                <div class="col-xs-12 col-md-8 no-gutters">
					<?php echo $this->melistoolcalendar_tool_calendar_content;?>
					<div class="recently-added d-block d-md-none">
						<?php echo $this->melistoolcalendar_tool_recent_added; ?>
					</div>
                </div>
            </div>
        </div>
    </div>
</div>

