<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="'. $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id.' '.$data_melisKey; ?>>
	<!-- Widget -->
	<div class="widget">
		<div class="widget-body">
			<div data-component>
				<div id="calendar"></div>
			</div>
		</div>
	</div>
	<!-- // Widget END -->
</div>