<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="'. $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id.' '.$data_melisKey; ?>>
	<div class="widget widget-inverse form-create">
	    <!-- Widget heading -->
		<div class="widget-head">
			<h4 class="heading"><?php echo $this->translate('tr_melistoolcalendar_form_create')?></h4>
		</div>
		<!-- // Widget heading END -->
		<div class="widget-body" >
            <?php
            	$form = $this->meliscalendar_event_title;
            	$form->prepare();
            	echo $this->form()->openTag($form); 
            	echo $this->melisFieldCollection($form);
            	echo $this->form()->closeTag(); 
            ?>
            <span class="help-block"><?php echo $this->translate('tr_melistoolcalendar_form_create_drag')?></span>
        </div>
	</div>
</div>