<?php

	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<div<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="widget-parent">
	<div class="widget-head">
		<div class="btn-group pull-right btn-group-xs">
			<a class="btn btn-default melis-refreshZone" data-toggle="tab"><i class="fa fa-refresh"></i></a>
		</div>
		<h3 class="heading"><i class="icon-stocks-up fa fa-fw"></i> <?= $this->translate('tr_meliscore_dashboard_Calendar'); ?></h3>
	</div>
	<div class="widget-body">
	        <div id="dashbaorad-calendar-tool"></div>
	</div>
</div>